Repository aukletio/Auklet-Client-C, pull requests merged in 2018-11, with the labels that each got.

#1 Migrate from ESG-USA to aukletio
  .circleci/config.yml
  .devops/calculate-app-version.sh
  .devops/calculateChangelogs.js
  .devops/deploy.sh
  .devops/determineVersionChange.js
  .devops/licenses.js
  .devops/post-release.sh
  .devops/ssh-config-aukletio
  .devops/test_and_coverage.sh
  .devops/updateProdReleasePr.sh
  .devops/validate-pr.sh
  .devops/validatePr.js
  .esg
  agent/requester.go
  api/api.go
  api/api_test.go
  broker/message.go
  broker/mqtt.go
  broker/mqtt_test.go
  broker/persistor_test.go
  cmd/client/main.go
  cmd/client/main_test.go
  compose/auklet/Dockerfile
  config/config.go
  device/device.go
  docker-compose.yml
  message/limiter.go
  message/limiter_test.go
  message/merge.go
  message/merge_test.go
  schema/convert.go
  schema/convert_test.go
  schema/schema.go
Labels: enhancement

#3 broker: fix profile topic name
  broker/message.go
Labels: bug

#4 Release Candidate Review
  .circleci/config.yml
  .devops/calculate-app-version.sh
  .devops/calculateChangelogs.js
  .devops/deploy.sh
  .devops/determineVersionChange.js
  .devops/licenses.js
  .devops/post-release.sh
  .devops/ssh-config-aukletio
  .devops/test_and_coverage.sh
  .devops/updateProdReleasePr.sh
  .devops/validate-pr.sh
  .devops/validatePr.js
  .esg
  agent/requester.go
  api/api.go
  api/api_test.go
  broker/message.go
  broker/mqtt.go
  broker/mqtt_test.go
  broker/persistor_test.go
  cmd/client/main.go
  cmd/client/main_test.go
  compose/auklet/Dockerfile
  config/config.go
  device/device.go
  docker-compose.yml
  message/limiter.go
  message/limiter_test.go
  message/merge.go
  message/merge_test.go
  schema/convert.go
  schema/convert_test.go
  schema/schema.go
Labels: release

#2 APM-1686: publish binaries to public S3 for all environments
  .devops/deploy.sh
  cmd/client/main.go
  config/config.go
  config/config_test.go
Labels: enhancement

#6 Release Candidate Review
  .devops/deploy.sh
  cmd/client/main.go
  config/config.go
  config/config_test.go
Labels: release

#7 Update instructions for bug reports
  README.md
  docs/CONTRIBUTING.md
Labels: devops

#8 Release Candidate Review
  README.md
  docs/CONTRIBUTING.md
Labels: release

#5 Release Review
  .circleci/config.yml
  .devops/calculate-app-version.sh
  .devops/calculateChangelogs.js
  .devops/deploy.sh
  .devops/determineVersionChange.js
  .devops/licenses.js
  .devops/post-release.sh
  .devops/ssh-config-aukletio
  .devops/test_and_coverage.sh
  .devops/updateProdReleasePr.sh
  .devops/validate-pr.sh
  .devops/validatePr.js
  .esg
  README.md
  agent/requester.go
  api/api.go
  api/api_test.go
  broker/message.go
  broker/mqtt.go
  broker/mqtt_test.go
  broker/persistor_test.go
  cmd/client/main.go
  cmd/client/main_test.go
  compose/auklet/Dockerfile
  config/config.go
  config/config_test.go
  device/device.go
  docker-compose.yml
  docs/CONTRIBUTING.md
  message/limiter.go
  message/limiter_test.go
  message/merge.go
  message/merge_test.go
  schema/convert.go
  schema/convert_test.go
  schema/schema.go
Labels: release

#9 APM-1692: Build client for ARM 6/7/8
  .devops/deploy.sh
Labels: enhancement
